# Generated by Django 4.2.20 on 2025-09-19 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    replaces = [('shoppingcart', '0001_initial'), ('shoppingcart', '0002_auto_20151208_1034'), ('shoppingcart', '0003_auto_20151217_0958'), ('shoppingcart', '0004_change_meta_options')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0046_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistrationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField(null=True)),
                ('mode_slug', models.CharField(max_length=100, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('invoice', models.IntegerField(null=True)),
                ('invoice_item', models.IntegerField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationCodeRedemption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(null=True)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('course_enrollment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.courseenrollment')),
                ('redeemed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('registration_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoppingcart.courseregistrationcode')),
            ],
        ),
    ]
